name: Build and deploy webapp

env:
  ARTIFACT_NAME: csye-webapp-${{ github.sha }}.zip
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
 
on:
  push:
    branches:
      - main
jobs:
    ci_cd:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Set up Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y wget zip unzip jq

      - name: Build Deployment Artifacts
        run: |
          mkdir codedeploy_artifact
          zip -r ${{env.ARTIFACT_NAME}} .
          pwd
          ls -al
          mv ${{env.ARTIFACT_NAME}} codedeploy_artifact/
          ls -al
          pwd
          cd codedeploy_artifact
          pwd
          ls -al

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{env.AWS_SECRET_KEY}}
          aws-region: ${{env.AWS_REGION}}
          
      - name: Build Packer
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: 'ami.json'
          varFile: 'dev-vars.json'
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
      - name: Copy Artifact to S3
        run: |
          aws s3 sync ./codedeploy_artifact s3://${{secrets.S3_CODEDEPLOY_BUCKET}}

      - name: Codedeploy API call
        run: |
          output=$(aws deploy create-deployment \
            --application-name ${{env.CODEDEPLOY_APPLICATION_NAME}} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{env.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME}} \
            --description "CSYE6255 - CodeDeploy" \
            --s3-location bucket=${{secrets.S3_CODEDEPLOY_BUCKET}},key=${{env.ARTIFACT_NAME}},bundleType=zip \
            --region ${{secrets.AWS_REGION}} \
            --output json)
            echo $output
            depId=$(echo $output | jq -r '.deploymentId')
            aws deploy wait deployment-successful --deployment-id $depId

      - name: Build Packer
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: 'ami.json'
          varFile: 'dev-vars.json'
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
