name: pull request check workflow

on:
   pull_request:
           branches:
                   - main

jobs:
    pr_check:
       runs-on: ubuntu-latest
       steps:
       - name: checkout repository
         uses: actions/checkout@v2
       - name: Set up Node JS
         uses: actions/setup-node@v2
         with:
           node-version: 14.x
           cache: npm
       - name: Install
         run: npm ci
              npm run build --if-present
       - name: Test
         run: npm test
       - name: Archive production artifacts
         uses: actions/upload-artifact@v2
         with:
           name: webservice_artifact
           path: |
             dist
             !dist/**/*.md
    packer:
      runs-on: ubuntu-latest
      steps:
      - name: Validate Packer template
        uses: hashicorp/packer-github-actions@master
        with:
          templateFile: 'ami.json'
          varFile: 'dev-vars.json'
        